version: '3'

services:
  install:
    image: node:lts-slim
    volumes:
      - ./:/app
    command: npm install  --prefix app
  node:
    build:
      context: .
    restart: always
    volumes:
      - /var/lib/fs/storage:/storage
      - ./:/app
    command: npm run start  --prefix app
    ports:
      - 5000:8090
    expose:
      - 8090
    env_file: 
      - .env